services:
  db:
    image: mysql:8.4.0
    command: --lc-time-names=pt_BR --mysql-native-password=ON
    environment:
      - TZ=${TZ}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 40s
      timeout: 10s
    init: true
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    restart: always
    volumes:
      - db:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=${TZ}
      - NODE_ENV=${NODE_ENV}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      retries: 5
      start_period: 40s
      timeout: 10s
    init: true
    ports:
      - "${SERVER_EXTERNAL_PORT}:3000"
      - "${SERVER_DEBUG_PORT}:9229"
    restart: always
    volumes:
      - ./server:/home/node/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      server:
        condition: service_healthy
    environment:
      - TZ=${TZ}
      - NODE_ENV=${NODE_ENV}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      retries: 5
      start_period: 40s
      timeout: 10s
    init: true
    ports:
      - "${CLIENT_EXTERNAL_PORT}:8080"
    restart: always
    volumes:
      - ./client:/home/node/app

volumes:
  db:
